### ISSUE TITLE
Incompatible with PHP 7.2

### ISSUE THREAD

**Issue by labudis** [intercom/oauth2-intercom#3]
Hi

2.x version of Google OAuth 2.0 Client Provider for The PHP League OAuth2-Client was released which is compatible with PHP 7.x. 

oauth2-intercom is not currently compatible with that version OAuth. Any chance an update could be released?

Thank you in advance.

**Comment by mmartinic** [comment]
hey @labudis 
@GabrielAnca is going to look into this

**Comment by GabrielAnca** [comment]
Hi @labudis :wave: I've been experimenting with PHP 7 and it seems that as you predicted it is a small change on our side. However, this implies an important upgrade of the `league/oauth2-client` library, which has a big set of breaking changes (see [2.0.0 onwards here](https://github.com/thephpleague/oauth2-client/blob/master/CHANGELOG.md#200)).

I'll be running some more testing to ensure this won't break anything :construction_worker_man: 

If you want to give it a try, you can do so by running `composer require intercom/oauth2-intercom:dev-ga/php7` or changing the version directly in your composer.json file to `dev-ga/php7`

**Comment by GabrielAnca** [comment]
Hey 👋 I just published a new release of this package (`2.0.0`). Please feel free to upgrade at any time.
