### ISSUE TITLE
fetchResourceOwnerDetails should be public

### ISSUE THREAD

**Issue by volkanozyilmaz** [intercom/oauth2-intercom#4]
Hi There, 

I need to get the app_id with access code from https://api.intercom.io/me. I found that function but it's protected, I hard coded it to make it public and now I can use it. Would you consider to make it public? 

Intercom.php:
public function fetchResourceOwnerDetails(AccessToken $token)

**Comment by volkanozyilmaz** [comment]
I changed my implementation, hard coded change will be a headache. I wrote another class but would be nice to have a public function. 

```
class IntercomOAuth extends Intercom
{
    public function resourceOwnerDetails(AccessToken $token)
    {
        return $this->fetchResourceOwnerDetails($token);
    }
}
```

**Comment by GabrielAnca** [comment]
Hi @volkanozyilmaz 👋 

I have been checking, and you should be able to achieve the same using the `getResourceOwner()` method. This is the code I'm using for testing:

```php
        $provider = new IntercomProvider([...]);
        $token = $this->getTokenFromSession();

        $user = $provider->getResourceOwner($token)->toArray();
        $appId = $user['app']['id_code'];
```

`getResourceOwner` is just a wrapper around `fetchResourceOwnerDetails`, so they should work equally 😃 

Please let me know if this helped.

**Comment by GabrielAnca** [comment]
Hey 👋 as the method `getResourceOwner` should do the same as you required, I'll be closing this issue now. If this didn't meet your requirements please feel free to reopen it 😃
